### ISSUE TITLE
Use fast-json-stringify to serialize

### ISSUE THREAD

**Issue by MrThanlon** [brillout/telefunc#123]
https://github.com/fastify/fast-json-stringify
Generate JSON schema for remote function args by typescript or jsdoc?

**Comment by brillout** [comment]
I'm quite happy with https://github.com/brillout/json-serializer so far. I don't see a rationale for moving away from it.

**Comment by MrThanlon** [comment]
1. Performance
2. Validation

**Comment by brillout** [comment]
Can you elaborate on each of these points?

**Comment by MrThanlon** [comment]
1. [fast-json-stringify](https://github.com/fastify/fast-json-stringify) is significantly faster than JSON.stringify() for small payloads. It requires a [JSON Schema Draft 7](https://json-schema.org/specification-links.html#draft-7) input to generate a fast stringify function.
2. By using JSON schema, type validation can be performed during deserialization.
3. By using JSON schema, extra properties in Object can be removed during serialization.

**Comment by brillout** [comment]
1. Is Telefunc a performance bottleneck for your application? Optimizing performance isn't a priority right now, but I'm happy to revisit if a user is reporting that Telefunc is a performance bottleneck.  
2. I believe semantic validation is best done by third-party tools. As for syntax validation, what's the advanced over https://telefunc.com/shield?
3. What's the use case?
