### ISSUE TITLE
svelte problem.

### ISSUE THREAD

**Issue by ohbob** [brillout/telefunc#127]
if files are not in the $lib/server/ folder, then they are shipped to the client, so if you got any db connections, they would be exposed to the client, right?

**Comment by ohbob** [comment]
if running a build, would that be bun or node, nothing really works as expected.

**Comment by brillout** [comment]
Have you tried? In principle and I'm fairly confident they aren't shipped to the client.

**Comment by brillout** [comment]
> ps, could not find any examples of svelte5, maybe there are some knowns?

Contribution welcome.
