### ISSUE TITLE
Add SvelteKit example

### ISSUE THREAD

**Issue by brillout** [brillout/telefunc#14]
Add example `examples/svelte` of using Telefunc + SvelteKit.

Telefunc supports Vite: there are no expected problems here.

**Comment by lkj4** [comment]
FWIW, just tried telefunc with SvelteKit and got _File '/home/[...]/src/lib/hello.telefunc.ts' is not a module. (ts 2306)_. In my vite.cofig.js I tried both: `plugins: [sveltekit(), telefunc()]` and `plugins: [telefunc(), sveltekit()]`.

**Comment by brillout** [comment]
SvelteKit isn't supported yet, see https://github.com/sveltejs/kit/issues/6700.

**Comment by brillout** [comment]
Actually, SvelteKit *is* supported, it's just that you can't save `.telefunc.js` files in `lib/server/`.

**Comment by brillout** [comment]
PR welcome to add a SvelteKit example.

**Comment by UnsolvedCypher** [comment]
I believe this can be closed, the example is already on the site

**Comment by brillout** [comment]
Indeed, thank you.
