### ISSUE TITLE
Auto-shield for Next

### ISSUE THREAD

**Issue by doronnac** [brillout/telefunc#35]
I'm using the current latest versions of next and telefunc.

I'll happily create a repro if this is news to you, I believe it's the best way to showcase it

**Comment by brillout** [comment]
Auto-shield currently only works with Vite. But it should be easy (trivial really) to add support for Next.

I'm currently working on Telefunc React Hooks for data fetching, I'll then have a look at adding auto-shield support for Next.js.

In the meantime, manually use the `shield()` function.

**Comment by brillout** [comment]
It's fixed in the `dev` branch, just let me polish 2-3 things but I publish a new version.

**Comment by brillout** [comment]
Released in `0.1.27`.
