### ISSUE TITLE
Make the docs TypeScript-first

### ISSUE THREAD

**Issue by lkj4** [brillout/telefunc#38]
Type-safe RPC is the actual innovation and outstanding feature of Telefunc. This is why people will use Telefunc, not because it's just another RPC lib. 

When I currently read the docs, I see all these weird type annotation but then, I read that there are only for non-SSR-stacks and then I see again JS everywhere. A bit confusing for people who just skim the docs.

Edit: Not sure if I was clear. I think that the primary audience are TS users who value and understand an end-to-end type-safe RPC stack without codegen and a lot of voodoo. Most other users just confuse this lib with a random RPC lib. So, once you have won the primary target you can extend to other cluster, such as JS users but I wouldn't target them first (because they just won't get the brilliance at glance).

**Comment by brillout** [comment]
Good idea.

Especially because it removes these `shield()` uses that TS users don't need (when Telefunc is able to infer it).

**Comment by lkj4** [comment]
Exactly! However, I found `shield()` and its naming extremely intuitive haha. You see rarely such good and semantic naming!

**Comment by brillout** [comment]
Haha, yea, I do care about simplicity & clarity :-). RPC deserves care :-).

**Comment by brillout** [comment]
There are couple of internal things I want to get done, I'll then update the docs to be TS first.

**Comment by brillout** [comment]
Done. The docs barely mention `shield()` anymore and the docs code snippets now predominantly use TypeScript instead.

I refactored the whole docs. The docs should now be much simpler to digest now.

Thanks for the feedback!
