### ISSUE TITLE
Offer cli tool for generating http wrapper module

### ISSUE THREAD

**Issue by bas080** [brillout/telefunc#43]
Considering that telefunc offers a simple solution. It would make sense to offer a simple way to build the http wrapper module easily. Currently it's tied to frameworks (which might help with popularity), but what if people want to setup their own thing. A simple bin/executable/cli tool would help those people.

**Comment by brillout** [comment]
It's tied to frameworks because Telefunc needs a transfomer.

But I'm thinking of a "vanilla" (i.e. without any transformer) way to use Telefunc. But you'll then loose a lot of niceties, most notably automatic runtime type check.
