### ISSUE TITLE
Colliding "types.ts" in generateShield

### ISSUE THREAD

**Issue by nitedani** [brillout/telefunc#44]
The project build fails if the user has a "types.ts" file in the project root.
```
[telefunc:transform] Did you mean to provide the overwrite option? A source file already exists at the provided file path: E:/Projects/app/types.ts
```
Can this file be named something else, unique to telefunc?

**Comment by brillout** [comment]
It’s fixed on the dev branch which I’ll release later today.

**Comment by brillout** [comment]
Release in `0.1.27`.
