### ISSUE TITLE
Using telefunc for initial data

### ISSUE THREAD

**Issue by jessielaf** [brillout/telefunc#55]
Hi,

Thank you for this awesome library!

I want to use telefunc to fetch the initial data as well as the data afterwards but it does not let me do that since I get the error:

```
[telefunc@0.1.40][Wrong Usage] Using Telefunc to fetch the initial data of your page is discouraged, see https://telefunc.com/initial-page-data
Error: [telefunc@0.1.40][Wrong Usage] Using Telefunc to fetch the initial data of your page is discouraged, see https://telefunc.com/initial-page-data
    at Object.getContext_sync [as getContext] (C:\Users\Jessie\projects\boiler\boiler-new\node_modules\telefunc\dist\cjs\node\server\getContext\sync.js:16:37)
    at Proxy.getContext (C:\Users\Jessie\projects\boiler\boiler-new\node_modules\telefunc\dist\cjs\node\server\getContext.js:13:34)
    at Module.onGetAll (C:/Users/Jessie/projects/boiler/boiler-new/src/routes/groups/groups.telefunc.ts:7:13)
    at load (C:/Users/Jessie/projects/boiler/boiler-new/src/routes/groups/+page.ts:6:14)
    at load_data (file:///C:/Users/Jessie/projects/boiler/boiler-new/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:111:43)
    at async file:///C:/Users/Jessie/projects/boiler/boiler-new/node_modules/@sveltejs/kit/src/runtime/server/page/index.js:193:13
```

The explanation on the site does not give me any detail as to why I cannot use telefunc as my initial data fetch. I do not want to write the same logic twice or reuse the same logic with the same end result.

Why did you decide to make this a error (you probably have a good reason for it) and is there a way to turn off this error message?

**Comment by brillout** [comment]
Because it needs deep integration with the UI framework. For example, with React, you need to use something like [`react-streaming`](https://github.com/brillout/react-streaming).

There is an example of fetching initial data with Telefunc using the stack Vite + vite-plugin-ssr + react-streaming if you're interested. Be aware that it's bleeding edge though.

I'll publish the example and update the doc page https://telefunc.com/initial-page-data later today.

**Comment by jessielaf** [comment]
@brillout thanks for the response! I forgot to mention am using sveltekit together with telefunc and I am using the `+page.svelte` to fetch initial data. The "svelte way" (in my limited svelte knowledge) of doing it would be to create a `+server.svelte` and creating an API endpoint meaning I have to use http anyways.

Looking forward to the documentation update!

**Comment by brillout** [comment]
Doesn't SvelteKit has something like Next.js's `getServerSideProps()`?

**Comment by brillout** [comment]
Let me know what you ended up doing.

I'll update the docs and publish the react-streaming example after I've finished VPS's V1 implementation.

**Comment by jessielaf** [comment]
@brillout I am pretty new to svelte and sveltekit. In the end it was me doing it wrong haha. I changed the server-side rendering to run the prisma commands directly and only use telefunc for api call such as creating a object.

**Comment by brillout** [comment]
👍. Which SvelteKit hook are you using? I'd be nice to document Next.js's `getServerSideProps()` SvelteKit equivalent on Telefunc's docs.

**Comment by jessielaf** [comment]
@brillout I used the guide on the website: https://telefunc.com/svelte-kit. Does that answer your question?

I have used +page.server.ts to load data (without the use of telefunc) https://kit.svelte.dev/docs/load.

When something needs to happen clientside I use telefunc.

**Comment by brillout** [comment]
Docs updated: https://telefunc.com/svelte-kit#initial-data.
