### ISSUE TITLE
Improve docs about automatic shield() generation

### ISSUE THREAD

**Issue by samuba** [brillout/telefunc#74]
When I adjust the official example like this no error is being thrown and the value is passed just fine to the telefunc'tion. Manually writing the shield guard works, though.
Only tested this in svelte-kit, might be a problem for other frameworks too. 

```
<div class="counter">
	<span>Counter: {count}</span>
	<button on:click={async () => {count = await onCounterIncrement("im a string, booh")}}>-1</button>
	<button on:click={async () => {count = await onCounterIncrement(+1)}}>+1</button>
	<button on:click={async () => {count = await onCounterIncrement(-10)}}>-10</button>
	<button on:click={async () => {count = await onCounterIncrement(+10)}}>+10</button>
</div>
```

Pretty scary to be honest. Would have expected automated tests that make sure validation works e2e.

**Comment by samuba** [comment]
Also when I have manual shield for this the error thrown on the client does not mention exactly what went wrong:
`Error: Aborted telefunction call onCounterIncrement()`

According to the docs it should be: `throws an error that `text` should be a `string` (instead of a `number`)`

The body of the network response looks like this: `{"ret":"!undefined","abort":true}`

**Comment by brillout** [comment]
The shield() automatic generation is done at build time so it only works
for production. Try in production and you should see the error as expected.

As for the abort message, check the server logs.

Marking this ticket as `documentation` as the docs should be improved to
mention all that.

**Comment by samuba** [comment]
Is there any way to enable this in local dev? I just deployed some changes and found that some telefunc calls fail in PROD now but worked out fine locally. No doubt it is because I did something messy in my code (no typescript error though), but still having that surprise only surface in production is difficult.

**Comment by brillout** [comment]
I agree but the automatic shield() generation takes a non-negligible amount of time. Slowing down dev isn't ideal either.

**Comment by brillout** [comment]
Let's track progress on documentation at https://github.com/brillout/telefunc/issues/104.
