### ISSUE TITLE
Several same-process Telefunc servers (e.g. microservice architecture)

### ISSUE THREAD

**Issue by iSuslov** [brillout/telefunc#83]
Hi, 
It would be nice to have the ability to use it in microservice architecture. 
Imagine you have `master` node, that orchestrates worker nodes located on remote hosts. It's nice to have `telefunc` involved to call remote functions in this case. As for now I think the only way to make it work is to isolate each telefunc singleton in a separate process which is not very convenient.

**Comment by brillout** [comment]
I agree having multiple Telefunc servers is important.

Although I'm thinking: isn't the whole idea of microservices to have several separate process in the first place?

I'm not sure I see the advantages of having several same-process Telefunc servers?

**Comment by iSuslov** [comment]
I've just realized that labeling it as "microservices" might have been overly ambitious. However, my specific scenario is situated within a field where one can effectively harness remote hardware without the need to concern oneself with communication intricacies. Imagine a node serving as the orchestrator, smoothly executing code on worker nodes.
