### ISSUE TITLE
Example of react native isn't updated to use the latest syntax for shield

### ISSUE THREAD

**Issue by pencilcheck** [brillout/telefunc#93]
In the telefunc website, under typescript manual it has recommended syntax for type inference. 
https://telefunc.com/shield#typescript-manual

However for some reason, the example doesn't uses that: https://github.com/brillout/telefunc/blob/main/examples/react-native/hello.telefunc.mjs

Update to the recommended syntax to avoid people getting lost on losing type inference capability

**Comment by brillout** [comment]
👍 Good point. Fixed.
