### ISSUE TITLE
Server side telefunc files monorepo support

### ISSUE THREAD

**Issue by pencilcheck** [brillout/telefunc#95]
```
Error: [telefunc@0.1.67][Wrong Usage] Your telefunc file `/Users/pencilcheck/Projects/project-new-expo/apps/expo/src/func/hello.telefunc.mjs` is not inlcuded in your project root `/Users/pencilcheck/Projects/project-new-expo/apps/expo/server`.
```

I also have a server that runs telefunc with express, and import the telefunc files manually using config.telefuncFiles variable.

I am migrating to monorepo and have to include those files outside the root project folder.

A quick digging let me into setting root and it seems to resolve this issue.
```
config.disableNamingConvention = true
{
  const require = createRequire(import.meta.url)
  // find all telefunc files automatically
  // https://stackoverflow.com/a/70114234/1742820
  const files = jetpack.find("../../func", { matching: "*.telefunc.mjs" });
  console.log(files);
  config.telefuncFiles = files.map(f => require.resolve(`./${f}`))

  const __filename = fileURLToPath(import.meta.url);
  const __dirname = path.dirname(__filename);
  config.root = path.resolve(__dirname, '..')
}
```

Is there a different recommended approach?

Actually, refer to a new thread I just created, I think I found the root cause and fixed it myself:

https://github.com/brillout/telefunc/issues/96

**Comment by brillout** [comment]
Error message improved: https://github.com/brillout/telefunc/commit/49e0ca323ab9410e3330c763bcf6b94203a2b0b6.

**Comment by brillout** [comment]
Correct me if I'm wrong but I think it works if you set `config.root` to the project root directory of your *client-side*, i.e. to `'/Users/pencilcheck/Projects/project-new-expo/apps/expo/src/'`.

Actually, I don't think setting `config.root` to the monorepo root `'/Users/pencilcheck/Projects/project-new-expo/apps/expo/'` works; I expect an error like/similar to the one you posted in your other issue.

I'll improve the docs to clarify that.

(Unrelated but I recommend following https://telefunc.com/event-based.)

**Comment by brillout** [comment]
Alright, AFAICT everything is fixed on Telefunc's side. Make sure to use the latest version for much improved error messages, and have a look at the new docs https://telefunc.com/root.

Note that you need to have all your `.telefunc.js` files live inside the client-side root directory (see Telefunc's new error messages for more information about this). Depending on what you want to achieve with your monorepo restructuring, this may be a blocker for you. Let me know if it's indeed a blocker; there may be a way to lift that restriction.
