### ISSUE TITLE
Is it possible to use .ts for telefunc in your react native example?

### ISSUE THREAD

**Issue by pencilcheck** [brillout/telefunc#96]
I have been struggling trying to convert mjs to ts in your react native. Tried a lot of ways but something always stop it from working, the culprit is mostly esm and commonjs stuff.

expo can't have "type" "module", and if I change the config to .cjs some libraries break so I also can't do that. Tried moving the server into a different folder and encounter telefunc bugs with monorepo support.

I think I am getting close by moving server into a sub folder of expo and have separate package.json (with "type": "module") and tsconfig.json, and I set config.root to the expo folder (which is parent folder) but still having issue loading ts

```
(node:38629) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/Users/pencilcheck/Projects/project-new-expo/apps/expo/src/func/hello.telefunc.ts:1
export { hello }
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:77:18)
    at wrapSafe (node:internal/modules/cjs/loader:1288:20)
    at Module._compile (node:internal/modules/cjs/loader:1340:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:345:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:294:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
```

Is there a way to make it work?

Btw
--------------------

Btw, I found out later that if I move the "server" outside and into the same level of "apps" I can make it work since it is reading the right tsconfig.json finally.

However I encounter another error:
```
$ node --loader ts-node/esm ./server.ts
(node:65037) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
Server running at http://localhost:3000
[ '../expo/src/func/hello.telefunc.ts' ]
[telefunc@0.1.67] Telefunction hello() (/src/func/hello.telefunc.ts) not found: the file /src/func/hello.telefunc.ts doesn't exist. Found `.telefunc.js` files:
  /expo/src/func/hello.telefunc.ts [✅ Exists]
  /src/func/hello.telefunc.ts [❌ Doesn't exist]
```

For monorepo support, is it possible to allow relaxed matching for finding the telefunc files?

--- new updates ---

I found that in your `loadTelefuncFilesFromConfig` function you are doing exact match for the path:
`https://github.com/brillout/telefunc/blob/165c9786ae8e6b44bddd48d7c119385c101800dd/telefunc/node/server/runTelefunc/loadTelefuncFilesFromConfig.ts#L24`
`!telefuncFilePath.includes(runContext.telefuncFilePath)` instead of `telefuncFilePath !== runContext.telefuncFilePath`

I also need to change it for the findTelefunction as well to use .includes instead of ===
`https://github.com/brillout/telefunc/blob/165c9786ae8e6b44bddd48d7c119385c101800dd/telefunc/node/server/runTelefunc/findTelefunction.ts#L99`

Once I changed it to .includes it seems to go back to the original error probably related to your @brillout/import

But if I import the files directly in my "server/server.ts", I don't see any errors. Is there something I'm missing with your @brillout/import?

--- another updates ---

in my tsconfig.json i have 
```
  "ts-node": {
    "experimentalSpecifierResolution": "node",
    "transpileOnly": true,
    "esm": true
  },

```

Looks like `"experimentalSpecifierResolution": "node",` makes it so .ts wouldn't work.

Turns out that it is not your import issue, it seems to be the behavior of the ts-node/esm loader I'm using. Essentially once I setup everything, I need to remove ".ts" when importing, then it will work.

I use `telefuncFilePathAbsolute.slice(0, -3)` at
`https://github.com/brillout/telefunc/blob/165c9786ae8e6b44bddd48d7c119385c101800dd/telefunc/node/server/runTelefunc/loadTelefuncFilesFromConfig.ts#L27`

I don't understand why ts-node doesn't allow import with ".ts" but removing it fixed the issue. and I can actually use it in react native with the setup I mentioned in this thread and other threads.

**Comment by pencilcheck** [comment]
Something happened, and not sure why it stops working so I started using `npx tsx` to run server.ts. So I need to make more modification to telefunc to make it work as tsx seems to make "export { hello }" assigned to default and that introduces a bit more bug to your telefunc.

This might be a separate issue.

**Comment by brillout** [comment]
Seems like most of the issues you're having are unrelated to Telefunc.

> is it possible to allow relaxed matching for finding the telefunc files?

The maching needs to be precise, in order to avoid false positives.

I think it's better we close this and open smaller more focused issues instead and, ideally, with minimal reproductions.

Keep me updated how it goes and contribution welcome to make `/examples/react-native/` use TypeScript.
