### ISSUE TITLE
call fails in vercel edge function

### ISSUE THREAD

**Issue by samuba** [brillout/telefunc#98]
When running the starter sveltekit project on vercel edge function with the [split option](https://kit.svelte.dev/docs/adapter-vercel) enabled, telefunc calls fail with the following error inside vercel. 
Somehow telefunc thinks the code is executed in a browser while it is running in the edge function.

Interestingly this does not happen if the whole project is bundled in a single edge function. It only occurs when splitting into multiple function is enabled or if you configure some routes explicitly to be deployed in an edge function.

![image](https://github.com/brillout/telefunc/assets/1148424/3b005449-370a-4770-8f42-07304e101b1e)

Code to reproduce: https://github.com/samuba/telefunc-vercel-edge
Its a sveltetkit starter project with an additional telefunc file and the [edge deployment configuration](https://github.com/samuba/telefunc-vercel-edge/blob/main/svelte.config.js).

**Comment by brillout** [comment]
You can only reproduce when using SvetleKit's `split` feature, correct? So I guess it's more of SvelteKit issue than a Telefunc one?

I just doubled checked the assertion, and everything looks correct on Telefunc's side.

Closing but let's re-open if there is some evidence it's related to Telefunc.

**Comment by samuba** [comment]
The split feature is just splitting the code into one function per route. The gist of it is that telefunc code runs in an edge function and wrongfully detects that it is running in the browser. I don't see how sveltekit could be responsible for this.

**Comment by brillout** [comment]
Feel free to dig yourself and PR welcome. But, again, I really doubt it's related to Telefunc.

**Comment by samuba** [comment]
Can you point me to where browser context detection happens?

**Comment by brillout** [comment]
Search for the assertion message.
